import React, { useState } from 'react';
import { Copy, Download, Check, FileCode, Terminal, ExternalLink } from 'lucide-react';

export default function BotExporter({ currentStrategy }) {
  const [copied, setCopied] = useState(false);

  const pythonBotCode = `"""
Kaggriculture Kaggle Competition Submission Bot
Strategy Preset: ${currentStrategy.name}
Generated by Kaggriculture AI Simulator
"""

import math
import random

# State tracking across turns
game_state = {
    'turn': 0,
    'land_quadrants': 1,
    'farmhands': 0,
    'last_action': None
}

def agent(observation, configuration):
    """
    Main entrypoint required by Kaggle Environments.
    - observation: dict containing current step, cash, plots, market_prices, inventory
    - configuration: dict containing game parameters
    """
    global game_state
    
    # Extract observation state (with safe defaults)
    step = observation.get('step', game_state['turn'])
    cash = observation.get('cash', 1000)
    market_prices = observation.get('market_prices', {
        'WHEAT': 12, 'CORN': 18, 'SOY': 25, 'MILK': 30, 'EGGS': 15, 'WOOL': 45
    })
    inventory = observation.get('inventory', {})
    plots = observation.get('plots', [])
    
    game_state['turn'] = step
    
    # Strategy Rules Configuration
    target_crops = ${JSON.stringify(currentStrategy.rules.targetCrops)}
    sell_multiplier = ${currentStrategy.rules.sellThresholdMultiplier}
    reinvest_land = ${currentStrategy.rules.reinvestInLand ? 'True' : 'False'}
    land_buy_threshold = ${currentStrategy.rules.landBuyThreshold || 600}
    
    actions = []
    
    # 1. Land Expansion Rule
    if reinvest_land and cash >= land_buy_threshold and game_state['land_quadrants'] < 4:
        game_state['land_quadrants'] += 1
        return {"action": "BUY_LAND", "cost": 500}
        
    # 2. Market Selling Rule
    for item, qty in inventory.items():
        if qty > 0 and item in market_prices:
            curr_price = market_prices[item]
            base_price = get_base_price(item)
            if curr_price >= base_price * sell_multiplier or step >= 710:
                return {
                    "action": "SELL_MARKET",
                    "item": item,
                    "quantity": qty
                }
                
    # 3. Crop Planting & Harvesting Rule
    for plot in plots:
        plot_id = plot.get('id')
        state = plot.get('state', 'EMPTY')
        
        if state == 'READY_TO_HARVEST':
            return {"action": "HARVEST", "plot_id": plot_id}
        elif state == 'PLANTED':
            if plot.get('moisture', 100) < 40 and cash >= 5:
                return {"action": "WATER", "plot_id": plot_id}
        elif state == 'EMPTY' and cash >= 15:
            crop_choice = target_crops[step % len(target_crops)]
            return {"action": "PLANT", "plot_id": plot_id, "crop": crop_choice}
            
    # Default Action: PASS / NOOP
    return {"action": "PASS"}

def get_base_price(item):
    base_prices = {'WHEAT': 12, 'CORN': 18, 'SOY': 25, 'MILK': 30, 'EGGS': 15, 'WOOL': 45}
    return base_prices.get(item, 10)
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(pythonBotCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([pythonBotCode], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'agent.py';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card p-6 rounded-2xl border border-slate-700/60 bg-slate-900/60 backdrop-blur-md space-y-6">
      
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            📦 Kaggle Competition Python Bot Exporter
          </h2>
          <p className="text-xs text-slate-400">Export active strategy ({currentStrategy.name}) as a Kaggle submission <code className="font-mono text-emerald-400">agent.py</code></p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={copyToClipboard}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition flex items-center gap-2"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard!' : 'Copy Code'}
          </button>

          <button
            onClick={downloadFile}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-emerald-500 hover:bg-emerald-600 text-slate-950 transition flex items-center gap-2 shadow-lg shadow-emerald-500/20"
          >
            <Download className="w-4 h-4" />
            Download agent.py
          </button>
        </div>
      </div>

      {/* Code Editor Box */}
      <div className="relative rounded-xl border border-slate-800 bg-slate-950 p-4 font-mono text-xs text-slate-300 overflow-x-auto max-h-[450px]">
        <pre>{pythonBotCode}</pre>
      </div>

      {/* Kaggle Submission Guide */}
      <div className="p-4 rounded-xl border border-emerald-500/30 bg-emerald-950/20 text-xs space-y-2">
        <h4 className="font-bold text-emerald-300 flex items-center gap-2">
          🚀 How to submit to Kaggle:
        </h4>
        <ol className="list-decimal list-inside space-y-1 text-slate-300">
          <li>Click <strong>Download agent.py</strong> above.</li>
          <li>Navigate to <a href="https://www.kaggle.com/competitions/kaggriculture/submit" target="_blank" rel="noreferrer" className="text-emerald-400 underline font-semibold inline-flex items-center gap-1">Kaggle Kaggriculture Submission <ExternalLink className="w-3 h-3" /></a>.</li>
          <li>Upload <code className="font-mono text-amber-300">agent.py</code> and click <strong>Submit</strong>.</li>
        </ol>
      </div>

    </div>
  );
}
