import React, { useState } from 'react';
import { Copy, Download, Check, FileCode, Terminal, ExternalLink } from 'lucide-react';

export default function BotExporter({ currentStrategy }) {
  const [copied, setCopied] = useState(false);

  const pythonBotCode = `"""
Official Kaggle Competition Submission Bot
Strategy Preset: ${currentStrategy.name}
Generated by Kaggriculture AI Simulator
Target Kaggle Environments Version
"""

import collections

COMMODITIES = {
    'WHEAT': {'seed_cost': 10, 'base_price': 25},
    'CARROT': {'seed_cost': 20, 'base_price': 35},
    'TOMATO': {'seed_cost': 50, 'base_price': 60},
    'STRAWBERRY': {'seed_cost': 100, 'base_price': 120},
    'MELON': {'seed_cost': 80, 'base_price': 250},
}

LAND_COSTS = [1000, 2000, 4000]

def agent(observation, configuration=None):
    """
    Main Entrypoint for Kaggle Environments
    """
    obs = observation if isinstance(observation, dict) else getattr(observation, '__dict__', {})
    
    player_id = obs.get('player', 0)
    farms = obs.get('farms', [{}, {}])
    me = farms[player_id] if player_id < len(farms) else {}
    
    money = me.get('money', 1000.0)
    tiles = me.get('tiles', [])
    farmer_pos = me.get('farmer', [0, 0])
    hands_pos = me.get('hands', [])
    unlocked_quads = me.get('unlocked_quadrants', ['NW'])
    
    market_obs = obs.get('market', {})
    prices = market_obs.get('prices', {})
    
    private_obs = obs.get('private', {})
    shed = private_obs.get('shed', {})
    seeds = private_obs.get('seeds', {})
    
    day = obs.get('day', 0)
    hour = obs.get('hour', 0)
    step = day * 24 + hour
    
    market_orders = []
    
    # 1. Land Expansion Rule
    quad_count = len(unlocked_quads)
    if quad_count < 4:
        next_cost = LAND_COSTS[quad_count - 1]
        if money >= next_cost + 200:
            market_orders.append(["BUY_LAND"])
            money -= next_cost

    # 2. Market Selling Rule
    for item, qty in shed.items():
        if qty > 0 and item in prices:
            base_price = COMMODITIES.get(item, {}).get('base_price', 25)
            if prices[item] >= base_price * ${currentStrategy.rules?.sellThresholdMultiplier || 1.15} or day >= 28:
                market_orders.append(["SELL", item, qty])

    # 3. Market Seed Buying Rule
    total_seeds = sum(seeds.values())
    if total_seeds < 5 and money >= 20:
        crop_choices = ${JSON.stringify(currentStrategy.rules?.targetCrops || ['WHEAT', 'CARROT'])}
        selected_crop = crop_choices[step % len(crop_choices)]
        cost = COMMODITIES.get(selected_crop, {}).get('seed_cost', 10)
        if money >= cost:
            market_orders.append(["BUY_SEED", selected_crop, 2])
            money -= cost * 2

    # 4. Farmer Spatial Action Selection
    fx, fy = farmer_pos[0], farmer_pos[1]
    current_tile = tiles[fy][fx] if (0 <= fy < len(tiles) and 0 <= fx < len(tiles[fy])) else None

    farmer_action = ["PASS"]

    if current_tile is not None and isinstance(current_tile, dict):
        kind = current_tile.get('kind')
        if kind == 'WEED':
            farmer_action = ["DIG"]
        elif kind == 'PLANT':
            if current_tile.get('yield_units', 0) > 0:
                farmer_action = ["HARVEST"]
            elif not current_tile.get('watered_today', False):
                farmer_action = ["WATER"]
    elif current_tile is None:
        available_crops = [c for c, q in seeds.items() if q > 0]
        if available_crops:
            farmer_action = ["PLANT", available_crops[0]]

    if farmer_action == ["PASS"]:
        move = get_best_move(fx, fy, tiles, seeds)
        if move:
            farmer_action = [move]

    hands_actions = [["PASS"] for _ in hands_pos]

    return {
        "farmer": farmer_action,
        "hands": hands_actions,
        "market": market_orders
    }

def get_best_move(fx, fy, tiles, seeds):
    if not tiles: return None
    rows, cols = len(tiles), len(tiles[0])
    queue = collections.deque([(fx, fy, [])])
    visited = {(fx, fy)}
    for dx, dy, move in [(0, -1, "NORTH"), (0, 1, "SOUTH"), (1, 0, "EAST"), (-1, 0, "WEST")]:
        nx, ny = fx + dx, fy + dy
        if 0 <= ny < rows and 0 <= nx < cols and tiles[ny][nx] != "LOCKED":
            return move
    return None
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(pythonBotCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([pythonBotCode], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'agent.py';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card p-6 rounded-2xl border border-slate-700/60 bg-slate-900/60 backdrop-blur-md space-y-6">
      
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            📦 Kaggle Competition Python Bot Exporter
          </h2>
          <p className="text-xs text-slate-400">Export 100% Kaggle-compliant submission code <code className="font-mono text-emerald-400">agent.py</code></p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={copyToClipboard}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition flex items-center gap-2"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard!' : 'Copy Code'}
          </button>

          <button
            onClick={downloadFile}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-emerald-500 hover:bg-emerald-600 text-slate-950 transition flex items-center gap-2 shadow-lg shadow-emerald-500/20"
          >
            <Download className="w-4 h-4" />
            Download agent.py
          </button>
        </div>
      </div>

      <div className="relative rounded-xl border border-slate-800 bg-slate-950 p-4 font-mono text-xs text-slate-300 overflow-x-auto max-h-[450px]">
        <pre>{pythonBotCode}</pre>
      </div>

      <div className="p-4 rounded-xl border border-emerald-500/30 bg-emerald-950/20 text-xs space-y-2">
        <h4 className="font-bold text-emerald-300 flex items-center gap-2">
          🚀 How to submit to Kaggle:
        </h4>
        <ol className="list-decimal list-inside space-y-1 text-slate-300">
          <li>Click <strong>Download agent.py</strong> above.</li>
          <li>Navigate to <a href="https://www.kaggle.com/competitions/kaggriculture/submit" target="_blank" rel="noreferrer" className="text-emerald-400 underline font-semibold inline-flex items-center gap-1">Kaggle Kaggriculture Submission <ExternalLink className="w-3 h-3" /></a>.</li>
          <li>Upload <code className="font-mono text-amber-300">agent.py</code> and click <strong>Submit</strong>.</li>
        </ol>
      </div>

    </div>
  );
}
