import React, { useState } from 'react';
import { Copy, Download, Check, FileCode, Terminal, ExternalLink } from 'lucide-react';

export default function BotExporter({ currentStrategy }) {
  const [copied, setCopied] = useState(false);

  const pythonBotCode = `"""
Official Kaggle Competition Submission Bot - Phase 2 Engine
Strategy Preset: ${currentStrategy.name}
Generated by Kaggriculture AI Simulator
"""

import collections

COMMODITIES = {
    'WHEAT': {'seed_cost': 10, 'base_price': 25, 'first_yield_days': 2},
    'CARROT': {'seed_cost': 20, 'base_price': 35, 'first_yield_days': 2},
    'TOMATO': {'seed_cost': 50, 'base_price': 60, 'first_yield_days': 7},
    'STRAWBERRY': {'seed_cost': 100, 'base_price': 120, 'first_yield_days': 10},
    'MELON': {'seed_cost': 80, 'base_price': 250, 'first_yield_days': 10},
    'EGG': {'base_price': 50},
    'MILK': {'base_price': 160},
    'WOOL': {'base_price': 200},
    'FERTILIZER': {'base_price': 100}
}
LAND_COSTS = [1000, 2000, 4000]

def get_seasonal_crop_choice(day, money, quad_count, step=0):
    if day < 10:
        return 'CARROT' if (step % 2 == 0 or money < 30) else 'WHEAT'
    elif day <= 22:
        if money >= 200 and step % 4 == 0:
            return 'MELON'
        elif money >= 120 and step % 3 == 0:
            return 'STRAWBERRY'
        elif money >= 60:
            return 'TOMATO'
        else:
            return 'CARROT'
    elif day <= 27:
        return 'CARROT' if step % 2 == 0 else 'WHEAT'
    else:
        return 'WHEAT' if day < 29 else None

def get_fibonacci_hire_cost(hires_today):
    fib = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
    return fib[min(hires_today, len(fib) - 1)]

def agent(observation, configuration=None):
    obs = observation if isinstance(observation, dict) else getattr(observation, '__dict__', {})
    player_id = obs.get('player', 0)
    farms = obs.get('farms', [{}, {}])
    me = farms[player_id] if player_id < len(farms) else {}
    
    money = me.get('money', 1000.0)
    tiles = me.get('tiles', [])
    farmer_pos = me.get('farmer', [0, 0])
    hands_pos = me.get('hands', [])
    unlocked_quads = me.get('unlocked_quadrants', ['NW'])
    hires_today = me.get('hires_today', 0)
    
    market_obs = obs.get('market', {})
    prices = market_obs.get('prices', {})
    inv_market = market_obs.get('inventory', {})
    
    private_obs = obs.get('private', {})
    shed = private_obs.get('shed', {})
    seeds = private_obs.get('seeds', {})
    
    day = obs.get('day', 0)
    hour = obs.get('hour', 0)
    step = day * 24 + hour
    
    market_orders = []
    
    # 1. Land Expansion Rule
    quad_count = len(unlocked_quads)
    if quad_count < 4 and money >= LAND_COSTS[quad_count - 1] + 150:
        market_orders.append(["BUY_LAND"])
        money -= LAND_COSTS[quad_count - 1]

    # 2. Fibonacci Farmhand Hiring Rule
    workload = sum(1 for r in tiles for t in r if t != "LOCKED" and (t is None or isinstance(t, dict)))
    hire_cost = get_fibonacci_hire_cost(hires_today)
    if workload >= 15 and money >= hire_cost + 150:
        market_orders.append(["HIRE"])
        money -= hire_cost
        hires_today += 1

    # 3. Market Selling & Town Demand Front-Running
    for item, qty in shed.items():
        if qty > 0 and len(market_orders) < 10:
            price = prices.get(item, COMMODITIES.get(item, {}).get('base_price', 25))
            base_price = COMMODITIES.get(item, {}).get('base_price', 25)
            if price >= base_price * ${currentStrategy.rules?.sellThresholdMultiplier || 1.05} or day >= 28:
                batch_qty = qty if day >= 28 else min(qty, 5)
                market_orders.append(["SELL", item, batch_qty])

    # 4. Seed Purchasing
    total_seeds = sum(seeds.values())
    if total_seeds < 6 and money >= 20 and len(market_orders) < 10:
        crop_choice = get_seasonal_crop_choice(day, money, quad_count, step)
        if crop_choice:
            cost = COMMODITIES.get(crop_choice, {}).get('seed_cost', 10)
            if money >= cost * 2:
                market_orders.append(["BUY_SEED", crop_choice, 2])

    # 5. Worker Spatial Actions
    all_workers = [farmer_pos] + list(hands_pos)
    reserved_targets = set()
    worker_actions = []

    for w_x, w_y in all_workers:
        act = ["PASS"]
        tile = tiles[w_y][w_x] if (0 <= w_y < len(tiles) and 0 <= w_x < len(tiles[0])) else None
        if isinstance(tile, dict):
            kind = tile.get('kind')
            if kind == 'WEED': act = ["DIG"]
            elif kind == 'PLANT':
                if tile.get('yield_units', 0) > 0: act = ["HARVEST"]
                elif not tile.get('watered_today', False): act = ["WATER"]
        elif tile is None:
            available = [c for c, q in seeds.items() if q > 0]
            if available: act = ["PLANT", available[0]]

        if act == ["PASS"]:
            move_dir, target = get_best_move(w_x, w_y, tiles, seeds, reserved_targets)
            if move_dir:
                act = [move_dir]
                if target: reserved_targets.add(target)

        worker_actions.append(act)

    return {
        "farmer": worker_actions[0] if worker_actions else ["PASS"],
        "hands": worker_actions[1:] if len(worker_actions) > 1 else [],
        "market": market_orders
    }

def get_best_move(fx, fy, tiles, seeds, reserved=None):
    if not tiles: return None, None
    if reserved is None: reserved = set()
    rows, cols = len(tiles), len(tiles[0])
    queue = collections.deque([(fx, fy, [])])
    visited = {(fx, fy)}
    for cx, cy, path in iter(queue.popleft, None):
        if len(path) > 12: break
        if 0 <= cy < rows and 0 <= cx < cols and tiles[cy][cx] != "LOCKED" and (cx, cy) not in reserved:
            if (cx, cy) != (fx, fy):
                t = tiles[cy][cx]
                if t is None and sum(seeds.values()) > 0: return path[0], (cx, cy)
                elif isinstance(t, dict) and (t.get('kind') == 'WEED' or t.get('yield_units', 0) > 0 or not t.get('watered_today', True)):
                    return path[0], (cx, cy)
        for dx, dy, move in [(0, -1, "NORTH"), (0, 1, "SOUTH"), (1, 0, "EAST"), (-1, 0, "WEST")]:
            nx, ny = cx + dx, cy + dy
            if 0 <= ny < rows and 0 <= nx < cols and (nx, ny) not in visited and tiles[ny][nx] != "LOCKED":
                visited.add((nx, ny))
                queue.append((nx, ny, path + [move]))
    return None, None
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(pythonBotCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const blob = new Blob([pythonBotCode], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'agent.py';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="glass-card p-6 rounded-2xl border border-slate-700/60 bg-slate-900/60 backdrop-blur-md space-y-6">
      
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
            📦 Kaggle Competition Python Bot Exporter
          </h2>
          <p className="text-xs text-slate-400">Export 100% Kaggle-compliant submission code <code className="font-mono text-emerald-400">agent.py</code></p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={copyToClipboard}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 transition flex items-center gap-2"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied to Clipboard!' : 'Copy Code'}
          </button>

          <button
            onClick={downloadFile}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-emerald-500 hover:bg-emerald-600 text-slate-950 transition flex items-center gap-2 shadow-lg shadow-emerald-500/20"
          >
            <Download className="w-4 h-4" />
            Download agent.py
          </button>
        </div>
      </div>

      <div className="relative rounded-xl border border-slate-800 bg-slate-950 p-4 font-mono text-xs text-slate-300 overflow-x-auto max-h-[450px]">
        <pre>{pythonBotCode}</pre>
      </div>

      <div className="p-4 rounded-xl border border-emerald-500/30 bg-emerald-950/20 text-xs space-y-2">
        <h4 className="font-bold text-emerald-300 flex items-center gap-2">
          🚀 How to submit to Kaggle:
        </h4>
        <ol className="list-decimal list-inside space-y-1 text-slate-300">
          <li>Click <strong>Download agent.py</strong> above.</li>
          <li>Navigate to <a href="https://www.kaggle.com/competitions/kaggriculture/submit" target="_blank" rel="noreferrer" className="text-emerald-400 underline font-semibold inline-flex items-center gap-1">Kaggle Kaggriculture Submission <ExternalLink className="w-3 h-3" /></a>.</li>
          <li>Upload <code className="font-mono text-amber-300">agent.py</code> and click <strong>Submit</strong>.</li>
        </ol>
      </div>

    </div>
  );
}
